version: '3'

services:
  dev:
    build:
      dockerfile: /Users/personal/dev/seniorescobar/buffup-devcontainers/base/Dockerfile

    volumes:
      - .:/alchemy-test:cached
      - /var/run/docker.sock:/var/run/docker.sock

    network_mode: host

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    command: /bin/sh -c "while sleep 1000; do :; done"
